#!/bin/bash

MD5_BIN=$(which md5)
BINARY=$0
VERBOSE=0

[ ! "${MD5_BIN}" ] && MD5_BIN=$(which md5sum)
[ ! "${MD5_BIN}" ] && echo "No md5 or md5sum executables." && exit 1

BASE_DIR=${HOME}/.rs
LEVEL1_DIR=${BASE_DIR}/`echo ${PWD} | $MD5_BIN | cut -b -4`
LEVEL2_DIR=${LEVEL1_DIR}/`echo $* | $MD5_BIN | cut -b -8`
FILENAME=${LEVEL2_DIR}/`echo ${PWD} $* | $MD5_BIN | cut -d ' ' -f 1`
MAX_NO_LINES=0
NO_LINES=1

[ ! -d ${BASE_DIR} ] && mkdir -p ${LEVEL2_DIR}
[ ! -d ${LEVEL1_DIR} ] && mkdir -p ${LEVEL2_DIR}
[ ! -d ${LEVEL2_DIR} ] && mkdir -p ${LEVEL2_DIR}

read MAX_NO_LINES < <(cat ${FILENAME} 2>/dev/null)

while read LINE
do
	if [ -z ${MAX_NO_LINES} ] || [ ${MAX_NO_LINES} -eq 0 ]
	then
		echo $LINE
	else
		PERCENTAGE=$(((100 * ${NO_LINES}) / ${MAX_NO_LINES}))
		[ ${PERCENTAGE} -gt 100 ] && PERCENTAGE=100
		printf "[%3d%%] " ${PERCENTAGE}
		echo "${LINE}"
	fi
	NO_LINES=$((${NO_LINES} + 1))
done < <($* 2>&1) # Really, I dont think is a good thing get the stderr...

echo $((${NO_LINES} - 1)) > $FILENAME
